// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmIvtybbRLxF_GnZSy7L1aslgLdV8wx8',
    appId: '1:880415272421:android:9d995bdf2cae8c6b4ad30c',
    messagingSenderId: '880415272421',
    projectId: 'beekind-71062',
    storageBucket: 'beekind-71062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVc9eKnwYy-RM34nCxfNrK8sSCClshzI',
    appId: '1:880415272421:ios:bc755bffbb4d71d94ad30c',
    messagingSenderId: '880415272421',
    projectId: 'beekind-71062',
    storageBucket: 'beekind-71062.firebasestorage.app',
    iosClientId: '880415272421-2063vitristbl6f45lh53rsguetl5lvj.apps.googleusercontent.com',
    iosBundleId: 'com.binatedigital.beekind',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2otAHEt8o_gCzLXVIvKSSWP25fpLCmfA',
    appId: '1:880415272421:web:44f94159bc75fec74ad30c',
    messagingSenderId: '880415272421',
    projectId: 'beekind-71062',
    authDomain: 'beekind-71062.firebaseapp.com',
    storageBucket: 'beekind-71062.firebasestorage.app',
    measurementId: 'G-EW1NJZ5VZG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVc9eKnwYy-RM34nCxfNrK8sSCClshzI',
    appId: '1:880415272421:ios:b7f50b8dbf1b2db14ad30c',
    messagingSenderId: '880415272421',
    projectId: 'beekind-71062',
    storageBucket: 'beekind-71062.firebasestorage.app',
    iosBundleId: 'com.binatedigital.beekind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2otAHEt8o_gCzLXVIvKSSWP25fpLCmfA',
    appId: '1:880415272421:web:22b74850c1ed29f54ad30c',
    messagingSenderId: '880415272421',
    projectId: 'beekind-71062',
    authDomain: 'beekind-71062.firebaseapp.com',
    storageBucket: 'beekind-71062.firebasestorage.app',
    measurementId: 'G-1LNM23Y4KV',
  );

}